name: CI

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - publish

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - run: "echo $FIREBASE_ADMIN_AUTH > $GOOGLE_APPLICATION_CREDENTIALS"
        env:
          FIREBASE_ADMIN_AUTH: { { secrets.FIREBASE_ADMIN_AUTH } }
          GOOGLE_APPLICATION_CREDENTIALS: "/tmp/firebase_admin_auth.json"
      - run: npm install
      - run: npm run export
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
